# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3735a6407faff0009d87d5f7b41adbb7"
application_url = "https://hose-quantities-arrived-narrow.trycloudflare.com"
embedded = true
name = "skusight"
handle = "skusight-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hose-quantities-arrived-narrow.trycloudflare.com/auth/callback",
  "https://hose-quantities-arrived-narrow.trycloudflare.com/auth/shopify/callback",
  "https://hose-quantities-arrived-narrow.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
